### ISSUE TITLE
Erreur lors du lancement API

### ISSUE THREAD

**Issue by Sigri44** [NebzHB/plugin-piHole#6]
Bonjour,

Erreur qui se déclenche à l'activation et désactivation du PiHole via le module (et pourtant la fonction s'exécute bien, le PiHole obéit) : 

`2018-08-13 20:48:06 | piHole | Erreur  exécution de la commande [Xxxxx][PiHole][Activer le filtrage] : Echec  de la requête HTTP : http://192.168.1.xxx/admin/api.php?enable&auth=xxxxxxx cURL error : Operation timed out after 2000 milliseconds with 0 bytes  received`

**Comment by NebzHB** [comment]
corrigé
